// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOOHBsuVqUYfo8UIB3wv-aUlP12HPEf04',
    appId: '1:8320079029:web:ad5f789f48271425285afc',
    messagingSenderId: '8320079029',
    projectId: 'cloud-messaging-644ab',
    authDomain: 'cloud-messaging-644ab.firebaseapp.com',
    storageBucket: 'cloud-messaging-644ab.firebasestorage.app',
    measurementId: 'G-L100XYMCBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqwb4H6L-1ud7eXnfINI-i1pOMic1QQps',
    appId: '1:8320079029:android:78e3118c2d32ffee285afc',
    messagingSenderId: '8320079029',
    projectId: 'cloud-messaging-644ab',
    storageBucket: 'cloud-messaging-644ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd_JPSf6VsdEIGOopZvc_Vg0gIixfu7E0',
    appId: '1:8320079029:ios:0d0ea882aba22ec4285afc',
    messagingSenderId: '8320079029',
    projectId: 'cloud-messaging-644ab',
    storageBucket: 'cloud-messaging-644ab.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd_JPSf6VsdEIGOopZvc_Vg0gIixfu7E0',
    appId: '1:8320079029:ios:0d0ea882aba22ec4285afc',
    messagingSenderId: '8320079029',
    projectId: 'cloud-messaging-644ab',
    storageBucket: 'cloud-messaging-644ab.firebasestorage.app',
    iosBundleId: 'com.example.cloudMessaging',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOOHBsuVqUYfo8UIB3wv-aUlP12HPEf04',
    appId: '1:8320079029:web:3b9cbdc392e22cac285afc',
    messagingSenderId: '8320079029',
    projectId: 'cloud-messaging-644ab',
    authDomain: 'cloud-messaging-644ab.firebaseapp.com',
    storageBucket: 'cloud-messaging-644ab.firebasestorage.app',
    measurementId: 'G-ZSP59C7LTM',
  );
}
